### ISSUE TITLE
!commands, !sounds not working

### ISSUE THREAD

**Issue by Penetrosity** [markokajzer/discord-soundbot#1]
It seems the bot is having an issue either typing to channel or PMing. I haven't been able to find out which.

I'm very new to this stuff so I'm pretty sure I'm wrong but this could have to do with the discord.js v9 update? http://hydrabolt.github.io/discord.js/#!/docs/tag/master/file/general/Updating%20your%20code

I'm too stupid to know how to update it to play nice so unfortunately I'm left with it just not working for now.

**Comment by markokajzer** [comment]
Hello! This is my first ever issue, so I'm quite excited. Thank you very much for bringing this issue to my attention! 👍

You are actually right. As per [this issue](https://github.com/hydrabolt/discord.js/issues/683#issuecomment-246158404) from discord.js itself, it seems like the Discord API has been changed and messages cannot be sent anymore. Upgrading to v9 will fix this issue, but it will take a little time because the library has changed quite a bit from what I can see. I was not aware of this problem, because I only use my bot very rarely these days and only play sounds.

There are midterms coming up, so it might take while to get this issue fixed. I will keep you up to date. Thanks again!

**Comment by markokajzer** [comment]
This issue should be fixed with the newest commit! :)
Sorry it took so long... Feel free to check it out, and leave any comment or suggestions!
