### ISSUE TITLE
Feature: display sounds with description and organized by category

### ISSUE THREAD

**Issue by rarguelloF** [markokajzer/discord-soundbot#18]
Hi!

Recently I created a similar application for creating sound bots, but your one is more complete, so I think I'll start using yours 😄 

However, I miss some features from my old one. One of the features was allowing the users to attach a yaml file associated to the sound files (with the same name as the sound and `.info` extension). Whenever I load the sounds from the folder, I also parse these  `.info` files and display a more complete help message when receiving the `!sounds` command (even allowing to display only for some category). These `.info` files are completely optional and the sounds which doesn't have one are grouped into an `Other` category.

Let me know if you like this feature and I could create a PR with it. 🎈

**Comment by markokajzer** [comment]
Hey man! Thanks for your interest in this project, that's nice to hear!

First of all, I also played with the idea of categories. I don't really see what else could be in these info files though. And also, there is already a (very simple) db that could hold that information instead of using an additional file per sound. Ultimately though, I don't think this is was worth implementing. But feel free to fork the repo and implement it for yourself. 😃 Sorry to disappoint you...

**Comment by rarguelloF** [comment]
Sure, don't worry and thank you anyway! :D
