### ISSUE TITLE
Publish package on NPM

### ISSUE THREAD

**Issue by lesander** [markokajzer/discord-soundbot#26]
Hi there!

Great work with the soundbot, thank you. 

While trying to upgrade from `0.8.0` to `1.0.0` I noticed that the repository isn't hosted on the npmjs.com registry. The `package.json` states `dicord_soundbot` as the name of the package, however it does not exist at https://www.npmjs.com/package/dicord_soundbot (or at any other link for that matter).

For more information on publishing a package on npmjs.com [see this article](https://docs.npmjs.com/getting-started/publishing-npm-packages).

**Comment by markokajzer** [comment]
Hey!

Thank you so much for using the bot, and thanks for the encouraging words. Means a lot.

As you can see from the [roadmap](https://github.com/markokajzer/discord-soundbot/projects/1#card-8167618), I am currently exploring how I can publish the bot to npm as I am really new to it. The problem I see here, is that currently the bot reads the config out of `./config` folder. This would not be possible anymore if the bot is installed via npm. So the config would need to be passed to a new instance of the SoundBot like so:

```javascript
const bot = new SoundBot(config);
bot.start();
```

Then the SoundBot needs to pass that config to all components. For that, some changes are necessary. :/

Since you upgraded to 1.0.0 let me tell you that the db.json that saves how many times each sound has been played cannot be used with 1.0.0. If you want to use your old database you need to rename `counts` to `sounds` and add `"tags": []` to each of the existing entries. Sorry for the inconvenience!

**Comment by markokajzer** [comment]
Happy to announce that this was finally implemented!  🎉

You can now find the package [on npm](https://www.npmjs.com/package/discord-soundbot).
