### ISSUE TITLE
Bot cuts away end of sound, doesn't play most sounds

### ISSUE THREAD

**Issue by lachsen** [markokajzer/discord-soundbot#48]
Installed this soundbot today on Windows. It seems to play some of our sounds, but others (especially short sounds) don't seem to work.

`(node:21500) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at item.request.gen.end (D:\soundbot\discord-soundbot-1.5.1\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:79:15)
    at then (D:\soundbot\discord-soundbot-1.5.1\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
`

**Comment by markokajzer** [comment]
Could you clarify what you mean by "don't seem to work"? Do you get a `DiscordAPIError: Missing Permissions` error specifically when playing short sounds? What is it that you are experiencing?

Generally, permissions are needed for deleting messages (if you have the `deleteMessages: true` config option), or to deafen the bot (if you have `deafen: true` config option).

Also, to my knowledge there is a problem with sounds cutting of a bit at the end with Node v10 and newer (supposedly due to some changes with how packets are processed). Might that be related to this? I could not figure out a fix for that yet, unfortunately :(

---

Completely unrelated, but are you _the_ lachsen, developer of CrossCode? I love that game man 😻

**Comment by lachsen** [comment]
Hey there,

yes, I'm a developer of CrossCode :D

We're currently looking for a new sound bot for our gamedev streams, since the old one doesn't work anymore.

I did update Node.js to the newest version so it's possible that the issues are because of that. I can try to downgrade Node.js for now and see if that helps, but this shouldn't be a long term solution.

Otherwise I can try this out again in more detail and let you know what happens.

**Comment by lachsen** [comment]
Hello again,

I gave it another try: The error message happens for pretty much every sound I try to play. Short sounds don't play at all, long sounds are cut away at the end and sometimes also have a "click" sounds when they start.

Also: I disabled "deleteMessages" and "deafen" options.

Node version is v10.16.2, so I can try to downgrade the version, though not sure I want to do that today. It might break some other stuff where we work with Node.js

**Comment by lachsen** [comment]
Okay, I now installed node.js version 8 (thanks to nvm it's easy to switch) and playback works mostly well now.

Very short sound still are a bit troublesome, for example this one:
https://www.dropbox.com/s/qq60zljyxf986o0/o.mp3?dl=0

Something I also notice in general: very often when you play a sound that has no silence in the beginning (like the o.mp3 sound), you will very shortly hear a cut-off beginning of the sound, then a short while of silence, followed by the full sound.

It also seems this mostly happend when you play a sound repeated times.

**Comment by markokajzer** [comment]
Hey! Thanks for the clarification and the example sound, very helpful to look further into the problem and much appreciated! I'll definitely look into it, but I fear that this has something to do with the underlying library I am using. Others are reporting similar issues with short sounds cutting off or having problems (see [here](https://github.com/discordjs/discord.js/issues/2546#issuecomment-403362126)). The issue seems to be fixed in an in-development version, but since it has been in development for quite some time and was not fully released yet, I decided against using it so far.

**Comment by prenetic** [comment]
I'm noticing the bot cutting off the last ~1 second of audio. I've actually had to go through and batch add 1 second of silence to a few hundred of them to work around this issue.

**Comment by markokajzer** [comment]
Did you try the work around suggested [here](https://github.com/markokajzer/discord-soundbot/issues/48#issuecomment-520180719) and on the Discord support server? Node v8 should make it work. Unfortunately this one is not on me, and there seems to be a problem with the underlying libs I use :(

**Comment by markokajzer** [comment]
I'll close this issue for now and leave it as documentation.

@lachsen: I'll keep the issue with very short sounds in mind, and see if that resolves itself when a new (major) version of discord.js is released.

**Comment by markokajzer** [comment]
This should actually now all be resolved. I upgraded to Discord.js v12 which was finally released after years and years. No more cutting off sounds, no more issues with short sounds.

Try `!combo o o o o o` with the sound you linked above :)
