### ISSUE TITLE
Error: Connection not established within 15 seconds.

### ISSUE THREAD

**Issue by jusplainmike** [markokajzer/discord-soundbot#58]
After a while I get this error. Also occurs when multiple people join within a few seconds. 
`Error occured!
 Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/root/discord-soundbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:256:27)
    at connectTimeout.client.setTimeout (/root/discord-soundbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:285:18)
    at Timeout.setTimeout (/root/discord-soundbot/node_modules/discord.js/src/client/Client.js:436:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

**Comment by markokajzer** [comment]
Hey, thanks for using the bot.

Can you explain a bit further? Do you mean when the bot runs a while it gets that error consistently? Do the people that join use entrance sounds?

Usually the error points to hiccups in the connection, e.g. let's say my WiFi is bad for a moment, the bot while time out like that. Another thing could be Discord server is in US but bot runs in EU.

**Comment by jusplainmike** [comment]
Yes four people with entrance music. The host server is in US and discord
server as well. I'm not convinced it isn't my VPS host connection.

**Comment by jusplainmike** [comment]
So how would I fix this issue without having to manually stop and restart the service?

**Comment by markokajzer** [comment]
Does the error happen consistenly 100% of the time?

If there is an error with the connection. This is really not on me, but rather on the library I am using. I would recommend you to try a different setup. Try your local setup and see if the error is reproducable. My bot is running on a server with a few people as well and as I said, I have only encountered this when my bot's connection was bad itself. If you find that it is _indeed_ reproducible, this might be something for the the [discord.js repo](https://github.com/discordjs/discord.js).

If you want to have a custom workaround for this issue... It does not seem like there is a reconnect function from what I can see [in the docs](https://discord.js.org/#/docs/main/stable/class/Client). On idea would be to terminate the process on `error`, e.g. ``client.on('error', () => process.exit())`, and use something like [pm2](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/), so that the process restarts automatically.

Again, this is something related to the library, not to the bot itself, so there is not much I can do for you, as I'd have to dig through the documentation as well.

**Comment by markokajzer** [comment]
Does the error happen consistenly 100% of the time?

I would recommend you to try a different setup. Try to setup the bot locally and see if the error is reproducable. My bot is running on a server with a few people as well and as I said, I have only encountered this when my bot's connection was bad itself. If you find that it is _indeed_ reproducible, this might be something for the the [discord.js repo](https://github.com/discordjs/discord.js), as it is not really on me, but rather on the library I am using under the hood. 

If you want to have a custom workaround for this issue... It does not seem like there is a reconnect function from what I can see [in the docs](https://discord.js.org/#/docs/main/stable/class/Client). One idea would be to terminate the process on `error`, e.g. ``client.on('error', () => process.exit())`, and use something like [pm2](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/), so that the process restarts automatically.

Again, this is something related to the library, not to the bot itself, so there is not much I can do for you, as I'd have to dig through the documentation as well.

**Comment by jusplainmike** [comment]
Thanks no the error doesn't happen on my local server. Or hasn't yet. I
believe it is the connection on my vps. Thanks for the insite on the error
issue I'm using systemd to run the service but it wouldn't restart on error
since the service is still running. I will explore your suggestion tonight
thank you. Other then that my discord really enjoys the bot thanks again.

**Comment by markokajzer** [comment]
While the bot has an error in that case, the process is still running. For systemd to restart it, you would have to terminate it first, I would say.

Thank you for the kind words, that is very much appreciated :)
