### ISSUE TITLE
Bot joins but does not play any sound on Windows

### ISSUE THREAD

**Issue by spartansniper619** [markokajzer/discord-soundbot#69]
Hello ! 

Sorry to bother you, I'm very very new to all of this so I'm sorry if it's an obvious mistake on my part. 

I followed steps by steps your instruction to manually build the bot and I think I've got it all fine, the bot seem very stable, no crash, the sounds list is what I put in the sounds folder path is good, and it join vocal as soon as I type a command in, the problem is that it does not play any sounds.

Nothing comes out of the bot so I checked out the command box to see is there's any error and there's is actually, just after I got the "Use the following URL to let the bot join your server!" here's what it says : 

![Capture](https://user-images.githubusercontent.com/61169001/74692519-ca353000-51e7-11ea-84d4-e2f51ac41c62.JPG)

I can't even understand if it's linked to my issue lol. 

Thanks in advance !

**Comment by markokajzer** [comment]
Heyya 👋 There are two issues. First your `clientId` in the `config.json` is incorrect. It looks like you are on a bit older version and not on master, so make sure it says `clientID` (notice the capitalized last two letters.) Make sure it **does not say `client_id=undefined`** in the `Use the following URL` output.

Another thing is that the installation of some of the dependencies failed as it looks like (Error says: Could not locate bindings file). Did you follow the guide int he wiki? Windows sometimes has a problem with the dependencies unfortunately. Try `yarn install` again and see if that fixes the error. If not you can try the following:

+ Delete `node_modules` folder
+ Run `yarn remove node-opus` 
+ Run `yarn add opusscript`
+ Run `yarn install`
+ Run `yarn start` again

Hopefully that should fix the issue on mobile.

Sorry for this hassle, I am working on a much much easier installation and configuration process.

**Comment by spartansniper619** [comment]
So ! Thank you very much ! 

To answer your question yes I followed every steps from the wiki for windows. 

So I did what you suggested and it's better, I don't know wich one of the solutions did it but the bot play sounds know ! But for the moment it dosen't play them all... Some won't function and sometime it plays only the begining or the end of other ones, it's buggy...

 I don't know if there's a solution to that too ?

**Comment by markokajzer** [comment]
Hey again! Glad you figured it out at least a bit. Let me tell you that 10 seconds is definitely too much, the bot should fire all sounds one after the other without any loading time. May I ask how many sounds you have? That could be an issue. Another reason could be the use of `opusscript`, instead of `node-opus`, which is highly disencouraged in the [discord.js docs](https://github.com/discordjs/discord.js#audio-engines), but should work for a small Windows setup.

As to the cutting away of the last bits of each sounds: Downgrade to Node.js v8 ([here](https://nodejs.org/dist/latest-v8.x/) is a link). There are some weird issues with newer versions. This is not specific to my bot, but rather to the combination of Node version, discord.js version (the underlying library I use), and voice support in general. And again, this is something I am actively looking into it and working on (see PR  #61).

I would recommend you to see if the downgrade to Node v8 helps (make sure to re-install all dependencies by completely removing the whole `node_modules` folder and running `yarn install` again), and trying to use `node-opus` instead of `opusscript`. As I also say in the wiki, I generally **highly recommend** running the bot on either a Linux or macOS based system, as there are oftentimes much less issues with it, e.g. I'm running the bot on a Raspberry Pi myself. You could also try the code from the mentioned PR and see if that helps you.

I hope that helps you. Right now the bot is unfortunately aimed at people that have somewhat experience with the technology, but I hope you can figure out a way. :)

**Comment by spartansniper619** [comment]
Sorry for the late answer ! 

So I can elaborate a little bit more, the bot seems to be very reactive the first 5-6 sounds when it goes online, but ultimately it goes down and down and it's very very slow to fire sounds.

To be faire there's a lot of sounds yes, 132 and it increase every day ! I'll make some test with onlu 5 sound on the folder to see (but when I had a bot very similar to yours back in 2016-17, I had already a undred + sounds and it was working perfectly fine ^^).

I'm sorry but I'm not sure to understand what you mean by " trying to use node-opus instead of opusscript", I'm not sure how to do that ? Sadly we only have windows here, I can't use anything else really... :/

I'll try to clear the folder and re-install with node v8, praying that the bot won't die xD

Thanks a lot for your help !

**Comment by markokajzer** [comment]
Let me just tell you that I have around 300 sounds, and it usually does not slow down, so your number should be ok. Sorry for your experience :(

What I meant is that you try to make the bot work without the changes we did from my [first comment](https://github.com/markokajzer/discord-soundbot/issues/69#issuecomment-587354573). When you go back to Node v8, try to use node-opus instead of opusscript and re-install all node_modules.

**Comment by spartansniper619** [comment]
Oh okay fuck me sometime I just stop my brain I swear xD

i'll give you update on the situation ^^
