### ISSUE TITLE
Changing avatar?

### ISSUE THREAD

**Issue by p00boy** [markokajzer/discord-soundbot#9]
Is there a directory within the files to be able to customize the bot's avatar? 

Great bot, exactly what I was looking for.

**Comment by markokajzer** [comment]
Great idea! I will implement this as soon as I have time next week!

**Comment by markokajzer** [comment]
Actually it is not possible to **remove** avatars with discord.js. I would like this to be possible as well before I implement avatars for the bot because the only way right now to remove avatars is manually via the Discord API which is quite bothersome. I actually [offered to implement](https://github.com/hydrabolt/discord.js/issues/1548) this missing feature for discord.js and will finish your request with the next version of discord.js

**Comment by markokajzer** [comment]
Sorry for the long silence... :'(

Good news! It is implemented as of now! Try it out and feel free to leave comments.
